spring:
  config:
    activate:
      on-profile: test,local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3ba9e2dd-041d-4104-b300-f8c25ee0d302.internal.kr1.mysql.rds.nhncloudservice.com:13306/pca_dev
    username: pca
    password: pca!@#123
---
