spring:
  application:
    name: privateCA
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.nhncloud.pca.config.JpaNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
